### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by seanbetts** [mermaid/AirSonos.app#1]
Hi,

Really please to see this app - I've been looking for something like this for ages!

Just tried installing and I keep just seeing 'Failed to Connect' in the menu

I've had a look at the log file and it just contains 'Searching for Sonos devices on network...'

Any thoughts?

In my set up I have a few Play 1s in different rooms and then a SoundBar and two Play 1's set up in the Living Room as surround sound speakers.

Thanks,

Sean

**Comment by mermaid** [comment]
I can't guarantee I'll be able to fix your problem [(It looks like others are having this problem too with the actual airsonos package)](https://github.com/stephen/airsonos/issues). However, I'll definitely try!

I've made a new release version that includes a way to make some diagnostic logs via the option+click menu. Can you update to that and run the diagnostic and get the logs to me?

**Comment by seanbetts** [comment]
Amazing, thanks for getting back to me so quick! I've updated to the new version and pulled down the logs:
[logs.txt](https://github.com/mermaid/AirSonos.app/files/705348/logs.txt)

**Comment by mermaid** [comment]
Alright, the mac sees the Sonos speakers, so thats good. I'll look into it soon, probably early next week though. Here's a few things you should try:
 - disable the firewall on the mac
 - disable the firewall on your router
 - stop antivirus (if any)
 - disable UPnP on your router

Those may or may not do anything, but if any of those work, I'll at least have a good direction of where to look for the issue/how to reproduce it myself.

**Comment by seanbetts** [comment]
Thanks, that's great. I don't have any firewalls enabled or antivirus running but I did just try to disable UPnP to see if that worked. It didn't make a difference but here's the log anyhow.
[logs.txt](https://github.com/mermaid/AirSonos.app/files/705443/logs.txt)

Thanks for all your help again!

**Comment by seanbetts** [comment]
Hi, did you ever get a chance to have a look at this?

**Comment by mermaid** [comment]
I have some, so far a have a possible theory. 
Try this
 - quit AirSonos
 - edit /Applications/AirSonos.app/Contents/Resources/app/node_modules/sonos/lib/sonos.js
 - line 789

 - change the ip address to your routers broadcast address:

```
this.socket.bind(function() {
    _this.socket.setBroadcast(true);
    _this.socket.send(PLAYER_SEARCH, 0, PLAYER_SEARCH.length, 1900, '239.255.255.250');
  });
```
for you I think it should be changed to
```
this.socket.bind(function() {
    _this.socket.setBroadcast(true);
    _this.socket.send(PLAYER_SEARCH, 0, PLAYER_SEARCH.length, 1900, '192.168.1.255');
  });
```
 - then boot up AirSonos again and see if it works

**Comment by mermaid** [comment]
Also, do you have a sonos bridge?
It seems like that might be what's causing the problem (I believe they aren't needed anymore anyways)

**Comment by seanbetts** [comment]
Hi,

Totally didn't realise I could remove my bridge. Have just done it and it's all now working seamlessly - AMAZING!

Thank you so much for all your help with this!

Sean

**Comment by mermaid** [comment]
No problem! It was pretty recently that you don't need a bridge anymore, I'll start an FAQ section or something so if other people run into this same issue they can get it all sorted out.

I'm glad we got it working!

**Comment by seanbetts** [comment]
Brilliant!

Just to be clear for anyone that reads this, I didn't implement any of the code changes merely removed the Sonos Bridge by putting the system in to Wireless mode.

Thanks again!

**Comment by mermaid** [comment]
No problem! I don't know if removing the bridge can potentially cause any issues with your sonos setup since I've never used a bridge, so if there ends up being any problems where you do have to use the bridge for something let me know and I think I could probably find a workaround

**Comment by seanbetts** [comment]
Will do.

I've just been testing the system and all good so far. Only thing I've found is there is a c.5 second delay between my iPhone and the speakers when play/pausing. Guessing that's because it's all routed through my Mac and back down to the speakers!

**Comment by mermaid** [comment]
Yeah, the 5s delay occurs to me to. I don't think theres much I can do about that slowness
